;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="Box.State.Damaged",DevComment="상자가 충격으로 인해 파손된 상태")
GameplayTagList=(Tag="Box.State.Delivered",DevComment="상자가 배송구역에 위치한 상태")
GameplayTagList=(Tag="Box.State.Held",DevComment="플레이어가 상자를 들고 있는 상태")
GameplayTagList=(Tag="Box.State.Spawned",DevComment="상자가 월드에 스폰되어 배치된 상태")

